// <auto-generated />
namespace Restoran.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seed_users_and_roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed_users_and_roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201806232157481_seed_users_and_roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
